# Generated by Django 3.2.4 on 2021-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'Short'), ('M', 'Medium'), ('L', 'Long')], max_length=30)),
                ('date', models.DateField()),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
