# Generated by Django 3.2.4 on 2021-07-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='left',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
    ]
